### PR TITLE
Adds a keyboard shortcut

### PR DESCRIPTION
**Pull request by jabranham**
Defaults to Ctrl+Shift+L, but allows the user to configure whatever they want

### CODE REVIEW

**Comment by sprig** [comment]
Sorry for taking a long time to reply.

I've been traveling and didn't have time to review the code, but it sounds
as a great addition!
Hopefully I will get to it this weekend.

Thanks!
-- 
-- 
Konstantin Kliakhandler
    http://slumpy.org
          )°) )°( (°(

**Comment by mdorman** [comment]
Is there something special I need to do to actually enable this, because it doesn't seem to be working for me.

**Comment by jabranham** [comment]
@mdorman - it works for me on Firefox 53.0.2.

It won't work if you're using FF 51 or previous. 

It does seem to be a little finecky in that if you must click the button physically the first time each firefox session. I *think* this may be related to the extension not using the new org protocol handler (yet?) #18 but haven't had time to investigate yet.

**Comment by sprig** [comment]
Oh, I haven't tested this on FF. Will need to check. What OS are you running on?

**Comment by jabranham** [comment]
It's definitely the warning that is issued from org-mode that triggers this funkyness. If you delete the warning from `org-protocol-check-filename-for-protocol` then it works exactly as expected.

**Pull request merged**
